P1_ThongphanhDuangboudda/AppStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ModelLayer.Models;
using RepositoryLayer;
using Microsoft.AspNetCore.Http;
using System.IO;
using BussinessLogicLayer;
using System.ComponentModel.DataAnnotations;

namespace AppStore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppStoreContext _context;
        private readonly ProductBL _productBL;

        public ProductsController(AppStoreContext context, ProductBL productBL)
        {
            _context = context;
            _productBL = productBL;
        }

        // GET: Products
        [HttpPost]
        public async Task<IActionResult> IndexSelectStore(int? id)
        {

            ViewData["StoreId"] = new SelectList( _context.Stores, "StoreId", "StoreId");

            return View( _productBL.GetProductsSync(1));
        }
        public async Task<IActionResult> Index(int storId)
        {
            //System.Diagnostics.Debug.WriteLine("Store Id ========= bbbb> " + ViewData["storeId"]);
           // System.Diagnostics.Debug.WriteLine("Store Id Xxxxxx ========= bbbb> " + storId);

            //var selectedValue = Request.Form["storeId"].ToString(); //this will get selected
            //System.Diagnostics.Debug.WriteLine("Store Id =========> " + selectedValue);
            if (storId > 0)
            {
               // System.Diagnostics.Debug.WriteLine("Store Id i=optional =========> " + storId);
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId");
            return View(_productBL.GetProductsSync(1));
        }
        public IActionResult SuggestionPage(int? id)
        {
           int customerId = (int)id;
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId");

            return View(_productBL.GetOrderSuggestions(customerId));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id, int quantity, bool reEnter)
        {
            System.Diagnostics.Debug.WriteLine("Products details conteroller =========> " + id + " q:   " + quantity);
            if (id == null)
            {
                return NotFound();
            }
      
           // System.Diagnostics.Debug.WriteLine("CustomerId =========> " + customerId);
            //var Id = HttpContext.Session.GetInt32(CustomerId);

            var product = await _context.Products
                .Include(p => p.store)
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            if (reEnter)
            {
               
                ViewData["er"] = "Please enter fewer items!!!";
                return View(product);
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,ProductName,ProductDescription,Category,Price,Quantity,StoreId,ImageData")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId", product.StoreId);
            return View(product);
        }
        //store
        public async Task<IActionResult> Store1(int? id)
        {
            System.Diagnostics.Debug.WriteLine("got store id :   " + id);
     
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId", product.StoreId);
            return View(product);
        }


        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId", product.StoreId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName,ProductDescription,Category,Price,Quantity,StoreId,ImageData")] Product product)
        {

            
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach(var file in Request.Form.Files)
                    {
                        MemoryStream ms = new MemoryStream();
                        file.CopyTo(ms);
                        product.ImageData = ms.ToArray();
                        ms.Close();
                        ms.Dispose();
                    }

                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId", product.StoreId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            System.Diagnostics.Debug.WriteLine("delete id is : " + id);
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.store)
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
        // GET: Products/Details/5
        public async Task<IActionResult> Checout(int? id, int aId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.store)
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        public async Task<IActionResult> Add(int? id, int quantity)
        {
            int storeId = (int)id;
            var Id = HttpContext.Session.GetInt32("_Id");
            System.Diagnostics.Debug.WriteLine("add is called Quantity is ===> " + quantity);
            bool notAvailable = true;
            notAvailable = _productBL.CheckProductAvailabilty((int)Id, storeId, quantity);
            if (notAvailable)
            {

    
               // ViewData["er"] = "Excess inventory!!, enter fewer items";
               // return View();
            }
           
            if (id == null)
            {
                return NotFound();
            }
            

            var product = await _context.Products
                .Include(p => p.store)
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            
            
            return View(product);
        }

    }
}

P1_ThongphanhDuangboudda/AppStore/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ModelLayer.Models;
using RepositoryLayer;
using BussinessLogicLayer;

namespace AppStore.Controllers
{
    public class StoresController : Controller
    {
        private readonly AppStoreContext _context;
        private readonly ProductBL _productBL;

        public StoresController(AppStoreContext context, ProductBL product)
        {
            _context = context;
            _productBL = product;
        }

        // GET: Stores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stores.ToListAsync());
        }

        // GET: Stores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }
            else
            {
                /*
                var products = _context.Products
                                .Where(x => x.StoreId == id)
                                 .AsNoTracking()
                                 .ToList();
                  */
                int num = (int)id;
               // int i = view.getId();
                System.Diagnostics.Debug.WriteLine("Specific store is called " + id);
                // var products = _productBL.GetProductsSync(1);
                // string url = string.Format($"/Products/Store1/{id}");
                var products = _productBL.GetProductsSyncByStoreId(num);
             
                return View(products);

            }

            // return View(store);
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StoreId,StoreName,Address,City,State")] Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Add(store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FindAsync(id);
            if (store == null)
            {
                return NotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StoreId,StoreName,Address,City,State")] Store store)
        {
            if (id != store.StoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(store.StoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var store = await _context.Stores.FindAsync(id);
            _context.Stores.Remove(store);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.StoreId == id);
        }
    }
}

P1_ThongphanhDuangboudda/AppStore/Views/Products/Create.cshtml
@model ModelLayer.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class ="form-control" asp-items="ViewBag.StoreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

P1_ThongphanhDuangboudda/AppStore/Views/Products/Delete.cshtml
@model ModelLayer.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.store.StoreId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

P1_ThongphanhDuangboudda/AppStore/Views/Products/Details.cshtml
@model ModelLayer.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <!--

    <div class="detailImage" style="background-image:url('@Model.ImageString')">
        <img src="@Model.ImageString" width="300px";  />

    </div>
            -->

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.store)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.store.StoreId)
        </dd>


    </dl>

</div>
<div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Customers" asp-action="Add" asp-route-id="@Model.ProductID" enctype="multipart/form-data" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
            
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Add to Cart" class="btn btn-primary" />
                <p id="errorMessage">@ViewData["er"]</p>
            </div>
        </form>
    </div>
</div>

P1_ThongphanhDuangboudda/AppStore/Views/Products/Edit.cshtml
@model ModelLayer.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductID" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class="form-control" asp-items="ViewBag.StoreId"></select>
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" type="file" id="file" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

P1_ThongphanhDuangboudda/AppStore/Views/Products/Index.cshtml
@model IEnumerable<ModelLayer.Models.Product>

@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

@{
    @inject IHttpContextAccessor HttpContextAccessor
    var isFiltered = @HttpContextAccessor.HttpContext.Session.GetString("_Name");
}


<p id="firstName" style="display: none"> @isFiltered</p>
<script>

    var content = document.getElementById("firstName").textContent;
    console.log("content is " + content);
    document.getElementById("Login").innerHTML = content;

</script>




<div class="text-center">
    <h1 class="display-4">Welcome To Troll Store</h1>
    <p>We care about you!!!</p>
</div>

<!--
<p>
    <a asp-action="Create">Create New</a>
</p
 -->

<form asp-controller="Stores" asp-action="Index" name="selectStore" asp-route-id="" method="post">
    <div class="form-group">


        <label class="control-label">Select Store</label>
        <select onchange="myFunction()" class="form-control" asp-items="ViewBag.StoreId"></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Shop Specific Store" class="btn btn-primary" />
    </div>
</form>



@foreach (var item in Model)
{
    <a class="productLink" asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductID" style="margin-bottom: 13px; margin-left: 13px; width: 18%">
        <div class="producColumn">

            <img class="image" src="@item.ImageString" style="width: 80%;  height: 200px; padding-top: 5% " />
            <p> Price: @item.Price</p>
        </div>

    </a>

}

<!--
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.store)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.store.StoreId)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProductID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

-->

P1_ThongphanhDuangboudda/AppStore/Views/Products/Store1.cshtml
@model IEnumerable<ModelLayer.Models.Product>

@{
    ViewData["Title"] = "Store1";
}

<h1>Store1</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.store)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageData)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageString)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.store.StoreId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageString)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

P1_ThongphanhDuangboudda/AppStore/Views/Products/SuggestionPage.cshtml
@model IEnumerable<ModelLayer.Models.Product>

@{
    ViewData["Title"] = "SuggestiionPage";
}

<h1>Suggested Products</h1>
@{ 
    int count = 0;
}
@foreach (var item in Model)
{
    count++;
    <a class="productLink" asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductID" style="margin-bottom: 13px; margin-left: 13px; width: 18%">
        <div class="producColumn">

            <img class="image" src="@item.ImageString" style="width: 80%;  height: 200px; padding-top: 5% " />
            <p> Price: @item.Price</p>
        </div>

    </a>
    if (count == 5) break;

}
<div style="text-align:center; background-color: lightblue; color: white; width: 95%; height: 40px; margin-left: 1.5%; padding: 10px;">
    <a  asp-controller="Products" asp-action="Index">Enter Troll Store</a>
</div>
